version: 0.2

env:
	variables:
		JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"

phases:
	install:
		commands:
			- apt-get update -y
			- apt-get install -y maven
	pre_build:
		commands:
			- echo Nothing to do in the pre_build phase...
	build:
		commands:
			- echo Build started on `date`
			- mvn clean install
	post_build:
		commands:
			- echo Build completed on `date`
artifacts:
	files:
		- target/HelloWorld-1.war
	discard-paths: yes
