version: 0.2

phases:
  install:
    commands:
      - echo Nothing to install, container image should have it all (based on what we selected)
  pre_build:
    commands:
      - echo Just listing basic information about the environment
      - which mvn
      - mvn -version
      - pwd
  build:
    commands:
      - echo Build started on `date`
      - mvn package
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Working on creating the tar ball with the WAR and AppSpec file for CodeDeploy
      - mkdir dep
      - cd dep
      - cp ../target/HelloWorld-1.war .
      - cp ../appspec.yml .
      - ls -al
      - tar -zcvf ../target/HelloWorld.tar.gz *.*
artifacts:
  files:
    - target/HelloWorld.tar.gz
  discard-paths: yes
